--s3 url --- s3://bucketsnowflakes3
  ---ddl
  CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));


CREATE DATABASE OUR_FIRST_DB;

CREATE STAGE OUR_FIRST_DB.PUBLIC.ORDERS_STAGE
URL = 's3://bucketsnowflakes3'
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1) ;


LIST @OUR_FIRST_DB.PUBLIC.ORDERS_STAGE ;



COPY INTO  OUR_FIRST_DB.PUBLIC.ORDERS
FROM @OUR_FIRST_DB.PUBLIC.ORDERS_STAGE
FILES =('OrderDetails.csv')
VALIDATION_MODE = RETURN_50_ROWS ;

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS ;


COPY INTO  OUR_FIRST_DB.PUBLIC.ORDERS
FROM @OUR_FIRST_DB.PUBLIC.ORDERS_STAGE
FILES =('OrderDetails.csv')
FORCE = TRUE

-----------------------

  CREATE STAGE OUR_FIRST_DB.PUBLIC.ORDERS_INT_STAGE
  FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1) ;

  LIST @OUR_FIRST_DB.PUBLIC.ORDERS_INT_STAGE ;


    CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V2 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));


    COPY INTO  OUR_FIRST_DB.PUBLIC.ORDERS_V2
FROM @OUR_FIRST_DB.PUBLIC.ORDERS_INT_STAGE  
PATTERN = '.*Employees.*\\.csv'


 COPY INTO  OUR_FIRST_DB.PUBLIC.ORDERS_V2
FROM @OUR_FIRST_DB.PUBLIC.ORDERS_INT_STAGE  
PATTERN = '.*order.*[.]csv'
purge=true ;

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_V2 ;
---------------------------------------------------------

CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.orders_ext_stage
    URL = 's3://snowflakebucket-copyoption/returnfailed/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

list @OUR_FIRST_DB.PUBLIC.orders_ext_stage ;




    CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V3 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

    select * from OUR_FIRST_DB.PUBLIC.ORDERS_V3;

    copy into OUR_FIRST_DB.PUBLIC.ORDERS_V3
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage
    validation_mode = return_errors ;

    copy into OUR_FIRST_DB.PUBLIC.ORDERS_V3
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage
    ON_ERROR = skip_file ;


     copy into OUR_FIRST_DB.PUBLIC.ORDERS_V3
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage
    ON_ERROR = continue  
    --force= true ;

     copy into OUR_FIRST_DB.PUBLIC.ORDERS_V3
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage
    VALIDATION_MODE = RETURN_5_ROWS ;


        CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V4 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(3),
    SUBCATEGORY VARCHAR(30));
   

 copy into OUR_FIRST_DB.PUBLIC.ORDERS_V4
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage
    ON_ERROR = continue  
    truncatecolumns = true ;


select * from OUR_FIRST_DB.PUBLIC.ORDERS_V4;



list @OUR_FIRST_DB.PUBLIC.orders_ext_stage ;

-----size
54622  > 50000    60000
10514   60000 < 640000  true
54597
54598


    CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_V5 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

     copy into OUR_FIRST_DB.PUBLIC.ORDERS_V5
    from @OUR_FIRST_DB.PUBLIC.orders_ext_stage
    ON_ERROR = continue  
    size_limit = 20000



    5 --1tb 
