
CREATE OR REPLACE STAGE OUR_FIRST_DB.PUBLIC.orders_ext_stage
    URL = 's3://snowflakebucket-copyoption/returnfailed/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

    list @OUR_FIRST_DB.PUBLIC.orders_ext_stage ;

    
   CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_v10 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

     COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_v10  
 FROM @OUR_FIRST_DB.PUBLIC.orders_ext_stage
 VALIDATION_mODE=RETURN_ERRORS;

  SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_v10 ;

   COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_v10  
 FROM @OUR_FIRST_DB.PUBLIC.orders_ext_stage
 VALIDATION_MODE = RETURN_ERRORS;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_ERRORS AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT REJECTED_RECORD FROM OUR_FIRST_DB.PUBLIC.ORDERS_ERRORS;

SELECT
  SPLIT_PART(REJECTED_RECORD, ',', 1) AS ORDER_ID,
  SPLIT_PART(REJECTED_RECORD, ',', 2) AS AMOUNT,
  SPLIT_PART(REJECTED_RECORD, ',', 3) AS PROFIT,
  SPLIT_PART(REJECTED_RECORD, ',', 4) AS QUANTITY,
  SPLIT_PART(REJECTED_RECORD, ',', 5) AS CATEGORY,
  SPLIT_PART(REJECTED_RECORD, ',', 6) AS SUBCATEGORY
FROM OUR_FIRST_DB.PUBLIC.ORDERS_ERRORS;