CREATE or replace TABLE OMS_DEV.BRONZE.CUSTOMER (
    CID INT,
    CNAME VARCHAR(10),
    ADDRESS VARCHAR(10)
);

INSERT INTO OMS_DEV.BRONZE.CUSTOMER (CID, CNAME, ADDRESS) VALUES
(1, 'Alice', 'New York'),
(2, 'Bob', 'Chicago'),
(3, 'Charlie', 'Dallas'),
(4, 'Diana', 'Seattle'),
(5, 'Eve', 'Boston');


update OMS_DEV.BRONZE.CUSTOMER
          set ADDRESS = 'blr'
    where cid = 4 ;
   
delete from OMS_DEV.BRONZE.CUSTOMER where cid = 5;

select * from  OMS_DEV.BRONZE.CUSTOMER ;

delete from   OMS_DEV.BRONZE.CUSTOMER;


CREATE or replace TABLE OMS_DEV.silver.CUSTOMER_tgt  clone
OMS_DEV.BRONZE.CUSTOMER ;
---------------------

CREATE or replace TABLE OMS_DEV.silver.CUSTOMER_tgt (
    CID INT,
    CNAME VARCHAR(10),
    ADDRESS VARCHAR(10)
);



select * from  OMS_DEV.silver.CUSTOMER_tgt  ;



-------------------------------
create or replace stream OMS_DEV.BRONZE.CUSTOMER_stream on table OMS_DEV.BRONZE.CUSTOMER ;

select * from OMS_DEV.BRONZE.CUSTOMER_stream;


MERGE INTO OMS_DEV.SILVER.CUSTOMER_TGT AS tgt
USING (
    SELECT CID, CNAME, ADDRESS, METADATA$ACTION, METADATA$ISUPDATE
    FROM OMS_DEV.BRONZE.CUSTOMER_STREAM
) AS src
ON tgt.CID = src.CID
WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN
    DELETE
WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE THEN
    UPDATE SET tgt.CNAME = src.CNAME, tgt.ADDRESS = src.ADDRESS
WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (CID, CNAME, ADDRESS) VALUES (src.CID, src.CNAME, src.ADDRESS);



create or replace task OMS_DEV.BRONZE.CUSTOMER_task
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('OMS_DEV.BRONZE.CUSTOMER_STREAM')
AS
MERGE INTO OMS_DEV.SILVER.CUSTOMER_TGT AS tgt
USING (
    SELECT CID, CNAME, ADDRESS, METADATA$ACTION, METADATA$ISUPDATE
    FROM OMS_DEV.BRONZE.CUSTOMER_STREAM
) AS src
ON tgt.CID = src.CID
WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN
    DELETE
WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE THEN
    UPDATE SET tgt.CNAME = src.CNAME, tgt.ADDRESS = src.ADDRESS
WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (CID, CNAME, ADDRESS) VALUES (src.CID, src.CNAME, src.ADDRESS);



show tasks;

ALTER TASK OMS_DEV.BRONZE.CUSTOMER_TASK RESUME;

ALTER TASK OMS_DEV.BRONZE.CUSTOMER_TASK SUSPEND;


create or replace task OMS_DEV.BRONZE.emp_task
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0/30 * * * * UTC'
as
delete from employee where status = 'inactive' ;

-------------------------------
-- SCD TYPE 2 IMPLEMENTATION
-------------------------------

CREATE OR REPLACE TABLE OMS_DEV.SILVER.CUSTOMER_SCD2 (
    CID INT,
    CNAME VARCHAR(10),
    ADDRESS VARCHAR(10),
    START_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    END_DATE TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE STREAM OMS_DEV.BRONZE.CUSTOMER_SCD2_STREAM ON TABLE OMS_DEV.BRONZE.CUSTOMER;

SELECT * FROM OMS_DEV.BRONZE.CUSTOMER_SCD2_STREAM;

MERGE INTO OMS_DEV.SILVER.CUSTOMER_SCD2 AS tgt
USING (
    SELECT CID, CNAME, ADDRESS, METADATA$ACTION, METADATA$ISUPDATE
    FROM OMS_DEV.BRONZE.CUSTOMER_SCD2_STREAM
) AS src
ON tgt.CID = src.CID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN
    UPDATE SET tgt.END_DATE = CURRENT_TIMESTAMP(), tgt.IS_CURRENT = FALSE
WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE THEN
    UPDATE SET tgt.END_DATE = CURRENT_TIMESTAMP(), tgt.IS_CURRENT = FALSE
WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (CID, CNAME, ADDRESS, START_DATE, END_DATE, IS_CURRENT)
    VALUES (src.CID, src.CNAME, src.ADDRESS, CURRENT_TIMESTAMP(), '9999-12-31', TRUE);

INSERT INTO OMS_DEV.SILVER.CUSTOMER_SCD2 (CID, CNAME, ADDRESS, START_DATE, END_DATE, IS_CURRENT)
SELECT src.CID, src.CNAME, src.ADDRESS, CURRENT_TIMESTAMP(), '9999-12-31', TRUE
FROM OMS_DEV.BRONZE.CUSTOMER_SCD2_STREAM src
WHERE src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE;

SELECT * FROM OMS_DEV.SILVER.CUSTOMER_SCD2 ORDER BY CID, START_DATE;

CREATE OR REPLACE TASK OMS_DEV.BRONZE.CUSTOMER_SCD2_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('OMS_DEV.BRONZE.CUSTOMER_SCD2_STREAM')
AS
MERGE INTO OMS_DEV.SILVER.CUSTOMER_SCD2 AS tgt
USING (
    SELECT CID, CNAME, ADDRESS, METADATA$ACTION, METADATA$ISUPDATE
    FROM OMS_DEV.BRONZE.CUSTOMER_SCD2_STREAM
) AS src
ON tgt.CID = src.CID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN
    UPDATE SET tgt.END_DATE = CURRENT_TIMESTAMP(), tgt.IS_CURRENT = FALSE
WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE THEN
    UPDATE SET tgt.END_DATE = CURRENT_TIMESTAMP(), tgt.IS_CURRENT = FALSE
WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (CID, CNAME, ADDRESS, START_DATE, END_DATE, IS_CURRENT)
    VALUES (src.CID, src.CNAME, src.ADDRESS, CURRENT_TIMESTAMP(), '9999-12-31', TRUE);

ALTER TASK OMS_DEV.BRONZE.CUSTOMER_SCD2_TASK RESUME;
