CREATE DATABASE OMS_DEV;

CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;


CREATE OR REPLACE STAGE OMS_DEV.PUBLIC.EMPLOYEE_STAGE
STORAGE_INTEGRATION = S3_INT1
URL = 's3://charishmareddy-snow-20/csv/'
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);

LIST @OMS_DEV.PUBLIC.EMPLOYEE_STAGE;

COPY INTO OMS_DEV.BRONZE.EMPLOYEES
FROM @OMS_DEV.PUBLIC.EMPLOYEE_STAGE
FILES = ('employee_data_1.csv')
FORCE=TRUE;

TRUNCATE TABLE OMS_DEV.BRONZE.EMPLOYEES;

CREATE OR REPLACE TABLE OMS_DEV.BRONZE.EMPLOYEES (
  id STRING,
  first_name STRING,
  last_name STRING,
  email STRING,
  city STRING,
  department STRING
);

CREATE TRANSIENT TABLE OMS_DEV.BRONZE.EMPLOYEES_V0 (
  id STRING,
  first_name STRING,
  last_name STRING,
  email STRING,
  city STRING,
  department STRING
);

CREATE TEMPORARY TABLE OMS_DEV.BRONZE.EMPLOYEES_TEMP (
  id STRING,
  first_name STRING,
  last_name STRING,
  email STRING,
  city STRING,
  department STRING
);

SHOW TABLES IN SCHEMA OMS_DEV.BRONZE;;

SELECT COUNT(*) 
FROM OMS_DEV.BRONZE.EMPLOYEES;

SELECT * FROM OMS_DEV.BRONZE.EMPLOYEES;

 SELECT * FROM OMS_DEV.BRONZE.EMPLOYEES_V0;

  SELECT * FROM OMS_DEV.BRONZE.EMPLOYEES_TEMP;