-- =========================================
-- CREATE DATABASE & SCHEMA
-- =========================================

CREATE DATABASE UDF_DATABASE;

CREATE SCHEMA UDF_DATABASE.UDF_SCHEMA;

USE DATABASE UDF_DATABASE;

USE SCHEMA UDF_SCHEMA;

-- =========================================
-- CREATE CUSTOMERS TABLE
-- =========================================

CREATE OR REPLACE TABLE UDF_DATABASE.UDF_SCHEMA.CUSTOMERS (
    CID NUMBER PRIMARY KEY,
    CNAME STRING,
    AMOUNT NUMBER(19,4),
    ADDRESS STRING,
    PHONE STRING,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    STATUS STRING
);

INSERT INTO UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
VALUES
(
    101,
    'RAVI',
    5000.0000,
    'BLR',
    '9876543210',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    'ACTIVE'
),
(
    102,
    'RAHUL',
    8000.0000,
    'HYD',
    '9876501234',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    'ACTIVE'
),
(
    103,
    'SNEHA',
    12000.0000,
    'BLR',
    '9123456780',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    'ACTIVE'
),
(
    104,
    'PRIYA',
    3000.0000,
    'CHN',
    '9988776655',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    'INACTIVE'
);

-- =========================================
-- INSERT CUSTOMER PROCEDURE
-- =========================================

CREATE OR REPLACE PROCEDURE UDF_DATABASE.UDF_SCHEMA.INSERT_CUSTOMER(
P_CID NUMBER,
P_CNAME STRING,
P_AMOUNT NUMBER(19,4),
P_ADDRESS STRING,
P_PHONE STRING
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
INSERT INTO UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
VALUES(
:P_CID,
:P_CNAME,
:P_AMOUNT,
:P_ADDRESS,
:P_PHONE,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP(),
'ACTIVE'
);
RETURN 'CUSTOMER INSERTED SUCCESSFULLY';
END;
$$;

-- =========================================
-- WITHDRAW PROCEDURE
-- =========================================

CREATE OR REPLACE PROCEDURE UDF_DATABASE.UDF_SCHEMA.WITHDRAW_AMOUNT(
    P_CID NUMBER,
    P_WITHDRAW_AMOUNT NUMBER(19,4)
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    BALANCE NUMBER(19,4);
    NEW_BALANCE NUMBER(19,4);

BEGIN

    SELECT AMOUNT
    INTO :BALANCE
    FROM (
        SELECT AMOUNT
        FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE CID = :P_CID
        LIMIT 1
    );

    IF (BALANCE >= P_WITHDRAW_AMOUNT) THEN

        UPDATE UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        SET 
            AMOUNT = AMOUNT - :P_WITHDRAW_AMOUNT,
            UPDATE_TIME = CURRENT_TIMESTAMP()
        WHERE CID = :P_CID;

        SELECT AMOUNT
        INTO :NEW_BALANCE
        FROM (
            SELECT AMOUNT
            FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
            WHERE CID = :P_CID
            LIMIT 1
        );

        RETURN 'WITHDRAW SUCCESSFUL. CURRENT BALANCE = ' || NEW_BALANCE;

    ELSE

        RETURN 'INSUFFICIENT BALANCE';

    END IF;

END;
$$;

CALL UDF_DATABASE.UDF_SCHEMA.WITHDRAW_AMOUNT(101,500);

-- =========================================
-- DEPOSIT PROCEDURE
-- =========================================

CREATE OR REPLACE PROCEDURE UDF_DATABASE.UDF_SCHEMA.DEPOSIT_AMOUNT(
    P_CID NUMBER,
    P_DEPOSIT_AMOUNT NUMBER(19,4)
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    CURRENT_BALANCE NUMBER(19,4);
    NEW_BALANCE NUMBER(19,4);

BEGIN

    SELECT AMOUNT
    INTO :CURRENT_BALANCE
    FROM (
        SELECT AMOUNT
        FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE CID = :P_CID
        LIMIT 1
    );

    UPDATE UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
    SET 
        AMOUNT = AMOUNT + :P_DEPOSIT_AMOUNT,
        UPDATE_TIME = CURRENT_TIMESTAMP()
    WHERE CID = :P_CID;

    SELECT AMOUNT
    INTO :NEW_BALANCE
    FROM (
        SELECT AMOUNT
        FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE CID = :P_CID
        LIMIT 1
    );

    RETURN 'DEPOSIT SUCCESSFUL. CURRENT BALANCE = ' || NEW_BALANCE;

END;
$$;

CALL UDF_DATABASE.UDF_SCHEMA.DEPOSIT_AMOUNT(101,1000);

-- =========================================
-- DISPLAY CUSTOMERS BY ADDRESS
-- =========================================

CREATE OR REPLACE PROCEDURE UDF_DATABASE.UDF_SCHEMA.GET_CUSTOMERS_BY_ADDRESS(
    P_ADDRESS STRING
)
RETURNS TABLE (
    CID NUMBER,
    CNAME STRING,
    AMOUNT NUMBER(19,4),
    ADDRESS STRING,
    PHONE STRING
)
LANGUAGE SQL
AS
$$
DECLARE
    RES RESULTSET;

BEGIN

    RES := (
        SELECT 
            CID,
            CNAME,
            AMOUNT,
            ADDRESS,
            PHONE
        FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE ADDRESS = :P_ADDRESS
    );

    RETURN TABLE(RES);

END;
$$;

CALL UDF_DATABASE.UDF_SCHEMA.GET_CUSTOMERS_BY_ADDRESS('BLR');
-- =========================================
-- DELETE INACTIVE CUSTOMER
-- =========================================

CREATE OR REPLACE PROCEDURE UDF_DATABASE.UDF_SCHEMA.DELETE_INACTIVE_CUSTOMER(
    P_CID NUMBER
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    CUSTOMER_COUNT NUMBER;

BEGIN

    SELECT COUNT(*)
    INTO :CUSTOMER_COUNT
    FROM (
        SELECT *
        FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE CID = :P_CID
        AND STATUS = 'INACTIVE'
    );

    IF (CUSTOMER_COUNT > 0) THEN

        DELETE FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE CID = :P_CID
        AND STATUS = 'INACTIVE';

        RETURN 'INACTIVE CUSTOMER DELETED SUCCESSFULLY';

    ELSE

        RETURN 'NO INACTIVE CUSTOMER FOUND';

    END IF;

END;
$$;

CALL UDF_DATABASE.UDF_SCHEMA.DELETE_INACTIVE_CUSTOMER(104);

SELECT *
FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
WHERE STATUS = 'ACTIVE';

-- =========================================
-- MINI STATEMENT PROCEDURE
-- =========================================

CREATE OR REPLACE PROCEDURE UDF_DATABASE.UDF_SCHEMA.GET_MINI_STATEMENT(
    P_CID NUMBER
)
RETURNS TABLE (
    CID NUMBER,
    CNAME STRING,
    AMOUNT NUMBER(19,4),
    UPDATE_TIME TIMESTAMP
)
LANGUAGE SQL
AS
$$
DECLARE
    RES RESULTSET;

BEGIN

    RES := (
        SELECT 
            CID,
            CNAME,
            AMOUNT,
            UPDATE_TIME
        FROM UDF_DATABASE.UDF_SCHEMA.CUSTOMERS
        WHERE CID = :P_CID
    );

    RETURN TABLE(RES);

END;
$$;

CALL UDF_DATABASE.UDF_SCHEMA.GET_MINI_STATEMENT(101);


