CREATE DATABASE OUR_FIRST_DB1 ;
CREATE SCHEMA PUBLIC1 ;
   
  --s3 url --- s3://bucketsnowflakes3/OrderDetails.csv

  CREATE OR REPLACE TABLE OUR_FIRST_DB1.PUBLIC1.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

    COPY INTO OUR_FIRST_DB1.PUBLIC1.ORDERS
FROM 's3://bucketsnowflakes3/OrderDetails.csv'
FILE_FORMAT = (TYPE=CSV , SKIP_HEADER = 1)

SELECT * FROM OUR_FIRST_DB1.PUBLIC1.ORDERS ;


 
SELECT
    ORDER_ID,
    SUM(CASE WHEN PROFIT >= 0 THEN PROFIT ELSE 0 END) AS POSITIVE_PROFIT,
    SUM(CASE WHEN PROFIT < 0 THEN PROFIT ELSE 0 END) AS NEGATIVE_PROFIT
FROM OUR_FIRST_DB1.PUBLIC1.ORDERS
GROUP BY ORDER_ID 
ORDER BY ORDER_ID ;


WITH PROFIT_CTE AS (
    SELECT
        ORDER_ID,
        CASE WHEN PROFIT >= 0 THEN PROFIT ELSE 0 END AS POS_PROFIT,
        CASE WHEN PROFIT < 0 THEN PROFIT ELSE 0 END AS NEG_PROFIT
    FROM OUR_FIRST_DB1.PUBLIC1.ORDERS
)
SELECT
    ORDER_ID,
    SUM(POS_PROFIT) AS POSITIVE_PROFIT,
    SUM(NEG_PROFIT) AS NEGATIVE_PROFIT
FROM PROFIT_CTE
GROUP BY ORDER_ID
ORDER BY ORDER_ID ;


SELECT
    ORDER_ID,
    PROFIT,
    SUM(CASE WHEN PROFIT >= 0 THEN PROFIT ELSE 0 END) OVER (PARTITION BY ORDER_ID) AS POSITIVE_PROFIT,
    SUM(CASE WHEN PROFIT < 0 THEN PROFIT ELSE 0 END) OVER (PARTITION BY ORDER_ID) AS NEGATIVE_PROFIT
FROM OUR_FIRST_DB1.PUBLIC1.ORDERS
ORDER BY ORDER_ID;
